//! JA3 / HTTP-2 fingerprint profiles.
//!
//! The primary source of truth is `data/collected_profiles.json`, generated by
//! `tools/gen_profiles.py` from real-device `ja3_info` captures. Because Chrome
//! permutes TLS extension order per connection, observations are grouped by
//! **JA4** (order insensitive) and the most frequent JA3 inside each group is
//! kept as the representative.
//!
//! When a request cannot be matched against the collected profiles we fall back
//! to the community profiles shipped by `wreq-util` (Chrome/Safari/Firefox/OkHttp).

use std::sync::atomic::{AtomicU64, Ordering};
use std::time::{SystemTime, UNIX_EPOCH};

use serde::Deserialize;
use wreq::header::{HeaderMap, HeaderName, HeaderValue};
use wreq::{
    AlpsProtos, CertCompressionAlgorithm, EmulationProvider, Http2Config, PseudoOrder,
    SettingsOrder, SslCurve, TlsConfig, TlsVersion,
};
use wreq_util::Emulation;

/// Embedded output of `tools/gen_profiles.py`.
const COLLECTED_PROFILES: &str = include_str!("../data/collected_profiles.json");

/// Chrome's TLS certificate compression algorithms (Brotli).
const CHROME_CERT_COMPRESSION: &[CertCompressionAlgorithm] = &[CertCompressionAlgorithm::Brotli];

/// Chrome cipher order, used only when a profile maps to no known cipher.
const FALLBACK_CIPHER_LIST: &str = "TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256:TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384:TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384:TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256:TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256:TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA:TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA:TLS_RSA_WITH_AES_128_GCM_SHA256:TLS_RSA_WITH_AES_256_GCM_SHA384:TLS_RSA_WITH_AES_128_CBC_SHA:TLS_RSA_WITH_AES_256_CBC_SHA";

/// Chrome signature algorithms, used only when a profile maps to no known sigalg.
const FALLBACK_SIGALGS_LIST: &str = "ecdsa_secp256r1_sha256:rsa_pss_rsae_sha256:rsa_pkcs1_sha256:ecdsa_secp384r1_sha384:rsa_pss_rsae_sha384:rsa_pkcs1_sha384:rsa_pss_rsae_sha512:rsa_pkcs1_sha512";

/// Chrome's default curve order.
const FALLBACK_CURVES: [SslCurve; 3] = [SslCurve::X25519, SslCurve::SECP256R1, SslCurve::SECP384R1];

/// Chrome style header order, used only when a captured profile has none.
const FALLBACK_HEADER_ORDER: [&str; 13] = [
    "sec-ch-ua-platform",
    "user-agent",
    "sec-ch-ua",
    "sec-ch-ua-mobile",
    "accept",
    "sec-fetch-site",
    "sec-fetch-mode",
    "sec-fetch-dest",
    "referer",
    "accept-encoding",
    "accept-language",
    "priority",
    "origin",
];

/// Chrome's HTTP/2 SETTINGS frame order (MaxConcurrentStreams before InitialWindowSize).
const CHROME_SETTINGS_ORDER: [SettingsOrder; 8] = [
    SettingsOrder::HeaderTableSize,
    SettingsOrder::EnablePush,
    SettingsOrder::MaxConcurrentStreams,
    SettingsOrder::InitialWindowSize,
    SettingsOrder::MaxFrameSize,
    SettingsOrder::MaxHeaderListSize,
    SettingsOrder::UnknownSetting8,
    SettingsOrder::UnknownSetting9,
];

/// Chrome sends `HEADERS` with stream dependency 0, weight 255, exclusive=true.
const CHROME_HEADERS_PRIORITY: (u32, u8, bool) = (0, 255, true);

// ---------------------------------------------------------------------------
// Wire model
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
#[allow(dead_code)]
struct ProfileFile {
    #[serde(default)]
    source: String,
    #[serde(default)]
    rows_parsed: u64,
    #[serde(default)]
    distinct_ja4: u64,
    profiles: Vec<Profile>,
}

/// One captured fingerprint profile.
#[derive(Debug, Clone, Deserialize)]
pub struct Profile {
    pub id: String,
    pub ja4: String,
    pub ja3: String,
    pub count: u64,
    pub tls: TlsProfile,
    /// Raw Akamai HTTP/2 fingerprint, e.g. `1:65536;2:0;...|15663105|0|m,a,s,p`.
    #[serde(default)]
    pub h2: String,
    #[serde(default)]
    pub ua: String,
    #[serde(default)]
    pub os: String,
    #[serde(default)]
    pub osv: String,
    #[serde(default)]
    pub model: String,
    #[serde(default)]
    pub chrome: String,
    #[serde(default)]
    pub country: String,
    /// Full observed header order (includes request specific headers).
    #[serde(default)]
    pub header_order: Vec<String>,
    /// Browser default headers worth replaying, as `[name, value]` pairs.
    #[serde(default)]
    pub headers: Vec<(String, String)>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct TlsProfile {
    pub ciphers: Vec<u16>,
    pub curves: Vec<u16>,
    pub sigalgs: Vec<u16>,
    #[serde(default)]
    pub extensions: Vec<u16>,
    #[serde(default)]
    pub alpn: String,
    #[serde(default)]
    pub tls_version: u8,
}

impl Profile {
    /// Chrome major version of the captured profile, if parseable.
    pub fn chrome_major(&self) -> Option<u32> {
        let major = self.chrome.split('.').next().unwrap_or("");
        major.parse().ok()
    }

    /// Stable key used to pool clients (one client per fingerprint + proxy).
    pub fn key(&self) -> String {
        format!("collected:{}", self.id)
    }

    /// Build the wreq TLS configuration for this profile.
    ///
    /// `typed_builder` tracks set fields in the type, so every setter must be
    /// called in a single expression; unset-able values are handled by always
    /// providing a concrete value (with Chrome defaults as fallback).
    pub fn tls_config(&self) -> TlsConfig {
        let mut ciphers: Vec<&str> = self
            .tls
            .ciphers
            .iter()
            .filter_map(|id| cipher_name(*id))
            .collect();
        if ciphers.is_empty() {
            ciphers = FALLBACK_CIPHER_LIST.split(':').collect();
        }

        let mut curves: Vec<SslCurve> = self.tls.curves.iter().filter_map(|id| curve(*id)).collect();
        if curves.is_empty() {
            curves = FALLBACK_CURVES.to_vec();
        }

        let mut sigalgs: Vec<&str> = self
            .tls
            .sigalgs
            .iter()
            .filter_map(|id| sigalg_name(*id))
            .collect();
        if sigalgs.is_empty() {
            sigalgs = FALLBACK_SIGALGS_LIST.split(':').collect();
        }

        TlsConfig::builder()
            .grease_enabled(true)
            .enable_ocsp_stapling(true)
            .enable_signed_cert_timestamps(true)
            .min_tls_version(TlsVersion::TLS_1_2)
            .max_tls_version(TlsVersion::TLS_1_3)
            // Chrome permutes ClientHello extensions per connection; this is what
            // makes JA3 vary while JA4 stays stable.
            .permute_extensions(true)
            .cert_compression_algorithm(CHROME_CERT_COMPRESSION)
            .cipher_list(ciphers.join(":"))
            .curves(curves)
            .sigalgs_list(sigalgs.join(":"))
            .alps_protos(self.alps_protos())
            // Chrome moved ALPS from 0x4469 (17513) to the new 0x44CD (17613)
            // codepoint; the captured profiles record which one the device sent.
            .alps_use_new_codepoint(self.tls.extensions.contains(&17613))
            // GREASE ECH (extension 65037) and pre_shared_key (extension 41).
            .enable_ech_grease(self.tls.extensions.contains(&0xfe0d))
            .pre_shared_key(self.tls.extensions.contains(&0x0029))
            .build()
    }

    /// Build the wreq HTTP/2 configuration parsed from the captured Akamai fingerprint.
    ///
    /// Every `Http2Config` field is `Option<T>` with an `into` setter, so absent
    /// settings can be passed through as `None` in a single builder chain.
    pub fn http2_config(&self) -> Option<Http2Config> {
        let parsed = H2Fingerprint::parse(&self.h2)?;
        let setting = |id: u16| {
            parsed
                .settings
                .iter()
                .find(|(key, _)| *key == id)
                .map(|(_, value)| *value)
        };

        Some(
            Http2Config::builder()
                // The Akamai fingerprint records the WINDOW_UPDATE *increment*;
                // hyper2 takes the absolute connection window, whose initial
                // value is the 65535 default.
                .initial_connection_window_size(
                    parsed
                        .connection_window
                        .map(|window| window.saturating_add(65_535)),
                )
                .header_table_size(setting(1))
                .enable_push(setting(2).map(|value| value != 0))
                .max_concurrent_streams(setting(3))
                .initial_stream_window_size(setting(4))
                .max_frame_size(setting(5))
                .max_header_list_size(setting(6))
                .unknown_setting8(setting(8).map(|value| value != 0))
                .unknown_setting9(setting(9).map(|value| value != 0))
                .headers_priority(CHROME_HEADERS_PRIORITY)
                .headers_pseudo_order(parsed.pseudo_order)
                .settings_order(CHROME_SETTINGS_ORDER)
                .build(),
        )
    }

    /// ALPS is only sent when the capture actually contained the ALPS extension
    /// (old codepoint 17513 or new codepoint 17613). Returning `None` keeps it
    /// out of the ClientHello so the extension set matches the capture.
    fn alps_protos(&self) -> Option<AlpsProtos> {
        let has_alps =
            self.tls.extensions.contains(&17513) || self.tls.extensions.contains(&17613);
        if !has_alps {
            return None;
        }
        Some(if self.tls.alpn == "h2" {
            AlpsProtos::HTTP2
        } else {
            AlpsProtos::HTTP1
        })
    }

    /// Browser default headers (sec-ch-ua, accept-language, priority, ...).
    pub fn default_headers(&self) -> HeaderMap {
        let mut map = HeaderMap::new();
        for (name, value) in &self.headers {
            if name.is_empty() || value.is_empty() || name.eq_ignore_ascii_case("user-agent") {
                continue;
            }
            if let (Ok(name), Ok(value)) = (
                HeaderName::from_bytes(name.as_bytes()),
                HeaderValue::from_str(value),
            ) {
                map.insert(name, value);
            }
        }
        map
    }

    /// Observed header order, pseudo headers stripped (they are handled by HTTP/2 config).
    pub fn headers_order(&self) -> Vec<HeaderName> {
        let mut seen = Vec::new();
        for name in &self.header_order {
            if name.starts_with(':') || name.eq_ignore_ascii_case("user-agent") {
                continue;
            }
            if let Ok(name) = HeaderName::from_bytes(name.as_bytes()) {
                if !seen.contains(&name) {
                    seen.push(name);
                }
            }
        }
        seen
    }

    /// Full emulation provider (TLS + HTTP/2 + headers) for this profile.
    pub fn provider(&self) -> EmulationProvider {
        let mut order = self.headers_order();
        if order.is_empty() {
            order = FALLBACK_HEADER_ORDER
                .iter()
                .map(|name| HeaderName::from_static(name))
                .collect();
        }

        EmulationProvider::builder()
            .tls_config(self.tls_config())
            .http2_config(self.http2_config())
            .default_headers(self.default_headers())
            .headers_order(order)
            .build()
    }
}

// ---------------------------------------------------------------------------
// ID -> BoringSSL name tables
// ---------------------------------------------------------------------------

/// JA3 cipher suite id -> BoringSSL/OpenSSL cipher name.
pub fn cipher_name(id: u16) -> Option<&'static str> {
    Some(match id {
        0x1301 => "TLS_AES_128_GCM_SHA256",
        0x1302 => "TLS_AES_256_GCM_SHA384",
        0x1303 => "TLS_CHACHA20_POLY1305_SHA256",
        0xc02b => "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
        0xc02f => "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        0xc02c => "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
        0xc030 => "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        0xcca9 => "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
        0xcca8 => "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
        0xc013 => "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
        0xc014 => "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
        0xc009 => "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA",
        0xc00a => "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA",
        0x009c => "TLS_RSA_WITH_AES_128_GCM_SHA256",
        0x009d => "TLS_RSA_WITH_AES_256_GCM_SHA384",
        0x002f => "TLS_RSA_WITH_AES_128_CBC_SHA",
        0x0035 => "TLS_RSA_WITH_AES_256_CBC_SHA",
        0x000a => "TLS_RSA_WITH_3DES_EDE_CBC_SHA",
        _ => return None,
    })
}

/// JA3 supported-group id -> BoringSSL curve.
///
/// X448 (30) and the larger FFDHE groups (258..260) are not exposed by the
/// BoringSSL build used here, so they are dropped. Everything Chrome sends in
/// the collected captures (4588/29/23/24) is supported.
pub fn curve(id: u16) -> Option<SslCurve> {
    Some(match id {
        23 => SslCurve::SECP256R1,
        24 => SslCurve::SECP384R1,
        25 => SslCurve::SECP521R1,
        29 => SslCurve::X25519,
        256 => SslCurve::FFDHE2048,
        257 => SslCurve::FFDHE3072,
        4588 => SslCurve::X25519_MLKEM768,
        _ => return None,
    })
}

/// JA3 signature-scheme id -> BoringSSL name.
///
/// Only names present in BoringSSL's `kSignatureAlgorithmNames` table may be
/// emitted: BoringSSL **hard-fails** `set_sigalgs_list` on an unknown name.
/// ML-DSA (0x0904/0x0905/0x0906), SHA-224 (0x0301/0x0303) and Ed448 (0x0808)
/// are not supported and are therefore dropped. This only affects JA4_c; JA3
/// never contains signature algorithms.
pub fn sigalg_name(id: u16) -> Option<&'static str> {
    Some(match id {
        0x0403 => "ecdsa_secp256r1_sha256",
        0x0503 => "ecdsa_secp384r1_sha384",
        0x0603 => "ecdsa_secp521r1_sha512",
        0x0804 => "rsa_pss_rsae_sha256",
        0x0805 => "rsa_pss_rsae_sha384",
        0x0806 => "rsa_pss_rsae_sha512",
        0x0401 => "rsa_pkcs1_sha256",
        0x0501 => "rsa_pkcs1_sha384",
        0x0601 => "rsa_pkcs1_sha512",
        0x0201 => "rsa_pkcs1_sha1",
        0x0203 => "ecdsa_sha1",
        0x0807 => "ed25519",
        _ => return None,
    })
}

// ---------------------------------------------------------------------------
// Akamai HTTP/2 fingerprint
// ---------------------------------------------------------------------------

#[derive(Debug, PartialEq, Eq)]
struct H2Fingerprint {
    settings: Vec<(u16, u32)>,
    connection_window: Option<u32>,
    pseudo_order: [PseudoOrder; 4],
}

impl H2Fingerprint {
    /// Parse `SETTINGS|WINDOW_UPDATE|PRIORITY|PSEUDO_ORDER`, e.g.
    /// `1:65536;2:0;4:6291456;6:262144|15663105|0|m,a,s,p`.
    fn parse(raw: &str) -> Option<Self> {
        let parts: Vec<&str> = raw.split('|').collect();
        if parts.len() < 4 {
            return None;
        }

        let mut settings = Vec::new();
        for entry in parts[0].split(';').filter(|s| !s.is_empty()) {
            let (id, value) = entry.split_once(':')?;
            settings.push((id.trim().parse().ok()?, value.trim().parse().ok()?));
        }

        let connection_window = parts[1].trim().parse().ok();

        let pseudo_order = parse_pseudo_order(parts[3])?;

        Some(Self {
            settings,
            connection_window,
            pseudo_order,
        })
    }
}

fn parse_pseudo_order(raw: &str) -> Option<[PseudoOrder; 4]> {
    let mut order = [PseudoOrder::Method, PseudoOrder::Authority, PseudoOrder::Scheme, PseudoOrder::Path];
    let mut len = 0;
    for token in raw.split(',') {
        let value = match token.trim() {
            "m" => PseudoOrder::Method,
            "a" => PseudoOrder::Authority,
            "s" => PseudoOrder::Scheme,
            "p" => PseudoOrder::Path,
            _ => continue,
        };
        if len < 4 {
            order[len] = value;
            len += 1;
        }
    }
    (len == 4).then_some(order)
}

// ---------------------------------------------------------------------------
// User agent parsing / selection
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Eq)]
struct UaInfo {
    chrome_version: Option<String>,
    chrome_major: Option<u32>,
    is_chrome: bool,
    is_firefox: bool,
    is_safari: bool,
}

impl UaInfo {
    fn parse(ua: &str) -> Self {
        let lower = ua.to_ascii_lowercase();
        let chrome_version = token_version(ua, "Chrome/")
            .or_else(|| token_version(ua, "Chromium/"))
            .or_else(|| token_version(ua, "CriOS/"));
        let chrome_major = chrome_version
            .as_deref()
            .and_then(|v| v.split('.').next())
            .and_then(|v| v.parse().ok());
        let is_firefox = lower.contains("firefox/");
        let is_chrome = chrome_version.is_some() || lower.contains("chromium/");
        let is_safari = !is_chrome && !is_firefox && lower.contains("safari/");
        Self {
            chrome_version,
            chrome_major,
            is_chrome,
            is_firefox,
            is_safari,
        }
    }
}

fn token_version(ua: &str, token: &str) -> Option<String> {
    let start = ua.find(token)? + token.len();
    let rest = &ua[start..];
    let end = rest
        .find(|c: char| !(c.is_ascii_digit() || c == '.'))
        .unwrap_or(rest.len());
    let value = &rest[..end];
    (!value.is_empty()).then(|| value.trim_end_matches('.').to_string())
}

/// Result of fingerprint selection for one request.
#[derive(Debug, Clone)]
pub enum Selected {
    /// A profile captured from real devices.
    Collected(Profile),
    /// A community emulation profile from `wreq-util`.
    Community(Emulation),
}

impl Selected {
    /// Pool key; clients are reused per (fingerprint, proxy).
    pub fn key(&self) -> String {
        match self {
            Selected::Collected(profile) => profile.key(),
            Selected::Community(emulation) => format!("community:{:?}", emulation),
        }
    }

    /// Human readable description for logs.
    pub fn describe(&self) -> String {
        match self {
            Selected::Collected(p) => format!(
                "collected:{} ja4={} chrome={} count={}",
                p.id, p.ja4, p.chrome, p.count
            ),
            Selected::Community(e) => format!("community:{:?}", e),
        }
    }
}

/// Registry of collected profiles plus community fallback.
///
/// Selection is lock-free: the RNG state is a single atomic, so the registry is
/// `Sync` and can be shared by all worker threads.
pub struct Registry {
    profiles: Vec<Profile>,
    total_weight: u64,
    seed: AtomicU64,
}

impl Registry {
    /// Parse the embedded collected profile file.
    pub fn from_embedded() -> Self {
        let file: ProfileFile = serde_json::from_str(COLLECTED_PROFILES)
            .expect("embedded data/collected_profiles.json must be valid");
        Self::new(file.profiles)
    }

    pub fn new(profiles: Vec<Profile>) -> Self {
        let total_weight = profiles.iter().map(|p| p.count.max(1)).sum();
        let seed = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_nanos() as u64)
            .unwrap_or(0x9e3779b97f4a7c15)
            | 1;
        Self {
            profiles,
            total_weight,
            seed: AtomicU64::new(seed),
        }
    }

    pub fn len(&self) -> usize {
        self.profiles.len()
    }

    pub fn is_empty(&self) -> bool {
        self.profiles.is_empty()
    }

    pub fn profiles(&self) -> &[Profile] {
        &self.profiles
    }

    pub fn get(&self, id: &str) -> Option<&Profile> {
        self.profiles.iter().find(|p| p.id == id)
    }

    /// Pick a fingerprint for the given request `User-Agent`.
    ///
    /// Order of preference:
    /// 1. a collected profile with the same Chrome major version,
    /// 2. a collected profile with the nearest Chrome major version,
    /// 3. a matching community profile (Chrome / Safari / Firefox),
    /// 4. the dominant collected profile.
    pub fn select(&self, ua: &str) -> Selected {
        let info = UaInfo::parse(ua);

        if info.is_chrome {
            if let Some(major) = info.chrome_major {
                if let Some(profile) = self.pick_collected(|p| p.chrome_major() == Some(major)) {
                    return Selected::Collected(profile);
                }
                if let Some(profile) = self.pick_nearest(major) {
                    return Selected::Collected(profile);
                }
            } else if let Some(profile) = self.pick_collected(|_| true) {
                return Selected::Collected(profile);
            }
            return Selected::Community(community_chrome(info.chrome_major));
        }

        if info.is_firefox {
            return Selected::Community(Emulation::Firefox139);
        }
        if info.is_safari {
            return Selected::Community(Emulation::Safari18_5);
        }

        // Unknown/absent UA: replay the dominant real-device profile.
        if let Some(profile) = self.pick_collected(|_| true) {
            return Selected::Collected(profile);
        }
        Selected::Community(Emulation::Chrome137)
    }

    /// Select by explicit profile id (used by tests and the verify CLI).
    pub fn select_by_id(&self, id: &str) -> Option<Selected> {
        self.get(id).cloned().map(Selected::Collected)
    }

    fn pick_collected<F: Fn(&Profile) -> bool>(&self, predicate: F) -> Option<Profile> {
        let candidates: Vec<&Profile> = self.profiles.iter().filter(|p| predicate(p)).collect();
        if candidates.is_empty() {
            return None;
        }
        let total: u64 = candidates.iter().map(|p| p.count.max(1)).sum();
        let mut roll = self.next_u64() % total.max(1);
        for profile in candidates {
            let weight = profile.count.max(1);
            if roll < weight {
                return Some(profile.clone());
            }
            roll -= weight;
        }
        self.profiles.iter().find(|p| predicate(p)).cloned()
    }

    fn pick_nearest(&self, major: u32) -> Option<Profile> {
        let best = self
            .profiles
            .iter()
            .filter_map(|p| p.chrome_major().map(|m| (m.abs_diff(major), m)))
            .min()
            .map(|(_, m)| m)?;
        self.pick_collected(|p| p.chrome_major() == Some(best))
    }

    /// xorshift64* — cheap per-process RNG, avoids pulling in the `rand` crate.
    fn next_u64(&self) -> u64 {
        let mut x = self.seed.load(Ordering::Relaxed);
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.seed.store(x, Ordering::Relaxed);
        x.wrapping_mul(0x2545_f491_4f6c_dd1d)
    }
}

fn community_chrome(major: Option<u32>) -> Emulation {
    match major {
        Some(v) if v >= 135 => Emulation::Chrome137,
        Some(134) => Emulation::Chrome134,
        Some(133) => Emulation::Chrome133,
        Some(132) => Emulation::Chrome132,
        Some(131) => Emulation::Chrome131,
        Some(130) => Emulation::Chrome130,
        Some(129) => Emulation::Chrome129,
        Some(128) => Emulation::Chrome128,
        Some(127) => Emulation::Chrome127,
        Some(126) => Emulation::Chrome126,
        Some(124) => Emulation::Chrome124,
        Some(123) => Emulation::Chrome123,
        Some(120) => Emulation::Chrome120,
        Some(119) => Emulation::Chrome119,
        Some(118) => Emulation::Chrome118,
        Some(117) => Emulation::Chrome117,
        Some(116) => Emulation::Chrome116,
        Some(114) => Emulation::Chrome114,
        Some(110) => Emulation::Chrome110,
        Some(109) => Emulation::Chrome109,
        Some(108) => Emulation::Chrome108,
        Some(107) => Emulation::Chrome107,
        Some(106) => Emulation::Chrome106,
        Some(105) => Emulation::Chrome105,
        Some(104) => Emulation::Chrome104,
        Some(101) => Emulation::Chrome101,
        Some(100) => Emulation::Chrome100,
        _ => Emulation::Chrome137,
    }
}

/// Convenience: build a client for a selected fingerprint.
pub fn build_client(selected: &Selected, proxy: &str) -> Result<wreq::Client, String> {
    let mut builder = wreq::Client::builder().redirect(wreq::redirect::Policy::none());
    if !proxy.is_empty() {
        let parsed = wreq::Proxy::all(proxy).map_err(|e| e.to_string())?;
        builder = builder.proxy(parsed);
    }
    builder = match selected {
        Selected::Collected(profile) => builder.emulation(profile.provider()),
        Selected::Community(emulation) => builder.emulation(*emulation),
    };
    builder.build().map_err(|e| e.to_string())
}

/// Small helper used by tests/CLI: describe the embedded registry.
pub fn embedded_summary() -> String {
    let registry = Registry::from_embedded();
    format!(
        "collected profiles: {} (total weight {})",
        registry.len(),
        registry.total_weight
    )
}

/// Normalize a JA3 string so that two handshakes with the same cipher and
/// extension *sets* compare equal even though Chrome permutes their order.
/// Only the cipher and extension fields are sorted; the curve order (which is
/// itself meaningful and stable for a given Chrome build) is preserved.
pub fn normalize_ja3(ja3: &str) -> String {
    let parts: Vec<&str> = ja3.split(',').collect();
    if parts.len() < 5 {
        return ja3.to_string();
    }
    let sort_field = |field: &str| {
        let mut values: Vec<&str> = field.split('-').filter(|v| !v.is_empty()).collect();
        values.sort_unstable();
        values.join("-")
    };
    format!(
        "{},{},{},{},{}",
        parts[0],
        sort_field(parts[1]),
        sort_field(parts[2]),
        parts[3],
        parts[4]
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_profiles_parse_and_are_non_empty() {
        let registry = Registry::from_embedded();
        assert!(
            registry.len() >= 10,
            "expected a meaningful collected library, got {}",
            registry.len()
        );
        let top = &registry.profiles()[0];
        assert!(top.ja4.starts_with("t13d"), "top ja4 = {}", top.ja4);
        assert!(!top.tls.ciphers.is_empty());
    }

    #[test]
    fn chrome_ua_matches_collected_profile() {
        let registry = Registry::from_embedded();
        let ua = "Mozilla/5.0 (Linux; Android 14; SM-A156E Build/UP1A.231005.007; wv) \
                  AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 \
                  Chrome/150.0.7871.181 Mobile Safari/537.36";
        match registry.select(ua) {
            Selected::Collected(profile) => {
                assert_eq!(profile.chrome_major(), Some(150));
                assert_eq!(profile.tls.curves, vec![4588, 29, 23, 24]);
            }
            Selected::Community(other) => panic!("expected collected profile, got {other:?}"),
        }
    }

    #[test]
    fn safari_ua_falls_back_to_community() {
        let registry = Registry::from_embedded();
        let ua = "Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X) \
                  AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1";
        match registry.select(ua) {
            Selected::Community(emulation) => {
                assert!(matches!(emulation, Emulation::Safari18_5))
            }
            Selected::Collected(profile) => panic!("expected community, got {}", profile.id),
        }
    }

    #[test]
    fn firefox_ua_falls_back_to_community() {
        let registry = Registry::from_embedded();
        let ua = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:139.0) Gecko/20100101 Firefox/139.0";
        match registry.select(ua) {
            Selected::Community(emulation) => {
                assert!(matches!(emulation, Emulation::Firefox139))
            }
            Selected::Collected(profile) => panic!("expected community, got {}", profile.id),
        }
    }

    #[test]
    fn older_chrome_uses_nearest_collected() {
        let registry = Registry::from_embedded();
        let ua = "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) \
                  Chrome/100.0.4896.127 Mobile Safari/537.36";
        match registry.select(ua) {
            Selected::Collected(profile) => assert!(profile.chrome_major().unwrap() < 150),
            Selected::Community(other) => panic!("expected collected profile, got {other:?}"),
        }
    }

    #[test]
    fn cipher_curve_sigalg_tables_cover_collected_profiles() {
        // Signature schemes BoringSSL does not implement; dropping them only
        // changes JA4_c (JA3 has no signature algorithms).
        const KNOWN_UNSUPPORTED_SIGALGS: [u16; 5] = [0x0301, 0x0303, 0x0904, 0x0905, 0x0906];

        let registry = Registry::from_embedded();
        for profile in registry.profiles() {
            for cipher in &profile.tls.ciphers {
                assert!(cipher_name(*cipher).is_some(), "unmapped cipher {cipher:#06x}");
            }
            for curve_id in &profile.tls.curves {
                assert!(curve(*curve_id).is_some(), "unmapped curve {curve_id}");
            }
            for sigalg in &profile.tls.sigalgs {
                assert!(
                    sigalg_name(*sigalg).is_some()
                        || KNOWN_UNSUPPORTED_SIGALGS.contains(sigalg),
                    "unmapped sigalg {sigalg:#06x}"
                );
            }
        }
    }

    #[test]
    fn akamai_fingerprint_parses() {
        let parsed = H2Fingerprint::parse("1:65536;2:0;4:6291456;6:262144|15663105|0|m,a,s,p")
            .expect("parse");
        assert_eq!(
            parsed.settings,
            vec![(1, 65536), (2, 0), (4, 6291456), (6, 262144)]
        );
        assert_eq!(parsed.connection_window, Some(15663105));
        assert_eq!(
            parsed.pseudo_order,
            [
                PseudoOrder::Method,
                PseudoOrder::Authority,
                PseudoOrder::Scheme,
                PseudoOrder::Path
            ]
        );
    }

    #[test]
    fn every_collected_profile_builds_a_provider() {
        let registry = Registry::from_embedded();
        for profile in registry.profiles() {
            let _ = profile.tls_config();
            let _ = profile.http2_config();
            let _ = profile.provider();
        }
    }

    /// Strongest offline check: actually create a BoringSSL context. This runs
    /// `set_cipher_list` / `set_sigalgs_list` / `set_curves_list`, which fail on
    /// names BoringSSL does not know (signature algorithms especially).
    #[test]
    fn every_collected_profile_builds_a_boring_ssl_context() {
        let registry = Registry::from_embedded();
        for profile in registry.profiles() {
            let selected = Selected::Collected(profile.clone());
            if let Err(err) = build_client(&selected, "") {
                panic!("profile {} failed to build client: {err}", profile.id);
            }
        }
    }

    #[test]
    fn ua_parsing_extracts_versions() {
        let info = UaInfo::parse("Mozilla/5.0 Chrome/150.0.7871.181 Mobile Safari/537.36");
        assert_eq!(info.chrome_major, Some(150));
        assert_eq!(info.chrome_version.as_deref(), Some("150.0.7871.181"));
        assert!(info.is_chrome && !info.is_safari);

        let safari = UaInfo::parse("Mozilla/5.0 Version/17.5 Mobile/15E148 Safari/604.1");
        assert!(safari.is_safari && !safari.is_chrome);

        let ios_chrome = UaInfo::parse("CriOS/120.0.6099.119 Mobile/15E148 Safari/604.1");
        assert!(ios_chrome.is_chrome);
        assert_eq!(ios_chrome.chrome_major, Some(120));
    }

    #[test]
    fn normalize_ja3_ignores_permutation_but_keeps_curves() {
        let a = "771,4865-4866,16-0-51,4588-29-23-24,0";
        let b = "771,4866-4865,51-16-0,4588-29-23-24,0";
        let c = "771,4865-4866,16-0-51,29-23-24,0";
        assert_eq!(normalize_ja3(a), normalize_ja3(b));
        assert_ne!(normalize_ja3(a), normalize_ja3(c));
    }
}
